### ISSUE TITLE
Removing obsolete tags

### ISSUE THREAD

**Issue by PropheticBird** [ikalnitsky/holocron#31]
If a user adds some tag to post, builds it and after that changes or removes the tag, it will still appear in the `paths.output/tags` directory.  
As I understand we will implement some kind of `view`, that will list all tags from that directory and all the tags will be links to the _"tag pages"_. 

So, with current behavior we will have obsolete tags in our tags array. We need to check somehow (perhaps on the view side), if a certain tag is still found in the blogpost that it refers to. 

I'm not sure whether it is a bug or not, we don't yet implemented the gui for tags functionality.

**Comment by ikalnitsky** [comment]
Hm.. Actually, I don't think it's a bug. I mean, yes, we indeed do not clear obsolete tags, still it doesn't matter because our pages just won't point to them. That means that tags will be exist only on filesystem and it's ok. Well, perhaps it's not ok but I'm sure that implementing additional mechanism for finding obsolete tags on filesystem will just complicate the logic and we don't get enough benefits from this.

If user wants a really *clear* build, he should do something like:

```bash
$ rm -rf _build/
$ holocron build
```

Perhaps we should add additional ``--clear`` flag to `build` command, but that's another story.

So I close this issue as invalid. Let's continue discussion if you have some objections, @PropheticBird.

**Comment by PropheticBird** [comment]
I think `--clear` flag is a great idea! Lets implement this for the `0.1.0`.
